### PR TITLE
Upload the initial of our website

### PR DESCRIPTION
**Pull request by WChihWen**
I upload the initial of our website.

### CODE REVIEW

**Comment by Titane73** [comment]
This is fine for this merge, and going forward let's make sure to make branches.  Annette, please touch in with your team to assure everyone is up to speed on branching and pull requests.

**Comment by Titane73** [comment]
Looks great to me.  Annette, leaving for you to review.

**Comment by tacostreets** [comment]
Thanks Ti. Will do.

**Comment by tacostreets** [comment]
This looks good. Merging.

**Pull request merged**
