### PR TITLE
Hijiri test #32

### PR DESCRIPTION
**Pull request by Hjr1993331**
Hello, I changed the border color and Iframe. 
I changed the blue border to lighter color, but do you have any recommendations for matching color in our google doc?

Also, this google doc is going to use webapptutorial.html as well?

Thank you very much in advance.

### CODE REVIEW

**Comment by tacostreets** [comment]
There will be two separate documents and links for each page and tutorial.

**Comment by tacostreets** [comment]
Also, The hex colors are in the app team doc #7ecaf6 The one pinned on the it115-app-team channel

**Comment by Hjr1993331** [comment]
Thank you for checking my pull request and collecting the color.
Ok, got it!

**Review by tacostreets — CHANGES_REQUESTED** [review]
Hi Hijiri, Please change the hex color to one of the colors listed on the app team doc.  blue  #7ecaf6  or dark grey #585858. I added both tutorial links as well. Please update the links in the Stack and App tutorial pages to match the team documents!

**Comment by tacostreets** [comment]
A new branch will be made. Closing and deleting

**Pull request closed without merging**
